version: '3'
services:
  db:
    image: mariadb
    container_name: n2s-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_USER: n2suser
      MARIADB_PASSWORD: n2spassword
      MARIADB_DATABASE: n2s
    volumes:
      - "./docker/create_db.sql:/docker-entrypoint-initdb.d/1.sql"
  adminer:
    image: phpmyadmin
    container_name: n2s-phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    container_name: n2s-web
    ports:
      - 5000:5000
    networks:
      - backend
  
networks:
  backend: